# Generated by Django 5.0.14 on 2025-11-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_id", models.CharField(db_index=True, max_length=64)),
                ("citation", models.CharField(max_length=128)),
                ("title", models.TextField(blank=True)),
                ("source_urls", models.JSONField(default=list)),
                ("jurisdiction", models.CharField(blank=True, max_length=8, null=True)),
                ("doc_type", models.CharField(default="policy", max_length=32)),
                ("topic", models.CharField(blank=True, max_length=64, null=True)),
                ("version_tag", models.CharField(db_index=True, max_length=32)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("html_sha256", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "policy_rule",
                "indexes": [
                    models.Index(
                        fields=["rule_id", "version_tag"],
                        name="policy_rule_rule_id_eddf82_idx",
                    )
                ],
                "unique_together": {("rule_id", "version_tag")},
            },
        ),
        migrations.CreateModel(
            name="PolicySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_tag", models.CharField(max_length=32)),
                ("path", models.TextField()),
                ("heading", models.TextField(blank=True)),
                ("text", models.TextField()),
                ("anchor", models.CharField(blank=True, max_length=128)),
                ("order_idx", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="policy_ingest.policyrule",
                    ),
                ),
            ],
            options={
                "db_table": "policy_section",
                "indexes": [
                    models.Index(
                        fields=["rule", "version_tag", "order_idx"],
                        name="policy_sect_rule_id_88760b_idx",
                    )
                ],
                "unique_together": {("rule", "version_tag", "path", "order_idx")},
            },
        ),
    ]
