# Generated by Django 5.0.14 on 2025-10-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyrule",
            name="doc_type",
            field=models.CharField(default="policy", max_length=32),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="topic",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
