# Generated by Django 5.0.14 on 2025-11-01 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public_core", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("rrc", "RRC"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="hybrid",
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "overlay_well_engagement",
            },
        ),
        migrations.CreateModel(
            name="CanonicalFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_key", models.CharField(max_length=128)),
                ("value", models.JSONField()),
                ("units", models.CharField(blank=True, max_length=32)),
                ("provenance", models.JSONField(default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_facts",
                        to="tenant_overlay.wellengagement",
                    ),
                ),
            ],
            options={
                "db_table": "overlay_canonical_facts",
            },
        ),
        migrations.CreateModel(
            name="PlanModification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_id", models.CharField(db_index=True, max_length=64)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("combine_plugs", "Combine Plugs"),
                            (
                                "replace_cibp_with_long_plug",
                                "Replace CIBP with Long Plug",
                            ),
                            ("generic_edit", "Generic Edit"),
                        ],
                        db_index=True,
                        default="generic_edit",
                        max_length=64,
                    ),
                ),
                ("request_payload", models.JSONField(default=dict)),
                ("result_diff", models.JSONField(default=dict)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_modifications",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_overlay_plan_modifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["plan_snapshot", "created_at"],
                        name="tenant_over_plan_sn_920b7b_idx",
                    ),
                    models.Index(
                        fields=["plan_id"], name="tenant_over_plan_id_2e7d8d_idx"
                    ),
                    models.Index(
                        fields=["operation"], name="tenant_over_operati_34e5d6_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tenant_over_created_d15a66_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("w2", "W-2"),
                            ("w15", "W-15"),
                            ("gau", "GAU"),
                            ("schematic", "Wellbore Schematic"),
                            ("formation_tops", "Formation Tops"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Absolute or media-relative path to stored file",
                        max_length=512,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "uploaded_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extracted_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="public_core.extracteddocument",
                    ),
                ),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_overlay_artifacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["artifact_type"], name="tenant_over_artifac_96ff42_idx"
                    ),
                    models.Index(
                        fields=["plan_snapshot", "created_at"],
                        name="tenant_over_plan_sn_330a6b_idx",
                    ),
                    models.Index(
                        fields=["extracted_document", "created_at"],
                        name="tenant_over_extract_daa067_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="tenant_over_created_057fa5_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wellengagement",
            index=models.Index(
                fields=["tenant_id", "well"], name="overlay_wel_tenant__32d1d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wellengagement",
            unique_together={("tenant_id", "well")},
        ),
        migrations.AddIndex(
            model_name="canonicalfacts",
            index=models.Index(
                fields=["engagement", "fact_key"], name="overlay_can_engagem_c6c874_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="canonicalfacts",
            unique_together={("engagement", "fact_key")},
        ),
    ]
