# Generated by Django 5.0.14 on 2025-10-04 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public_core", "0002_publicwelldepths_publiccasingstring_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("rrc", "RRC"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="hybrid",
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "overlay_well_engagement",
            },
        ),
        migrations.CreateModel(
            name="CanonicalFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_key", models.CharField(max_length=128)),
                ("value", models.JSONField()),
                ("units", models.CharField(blank=True, max_length=32)),
                ("provenance", models.JSONField(default=list)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_facts",
                        to="tenant_overlay.wellengagement",
                    ),
                ),
            ],
            options={
                "db_table": "overlay_canonical_facts",
            },
        ),
        migrations.AddIndex(
            model_name="wellengagement",
            index=models.Index(
                fields=["tenant_id", "well"], name="overlay_wel_tenant__32d1d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wellengagement",
            unique_together={("tenant_id", "well")},
        ),
        migrations.AddIndex(
            model_name="canonicalfacts",
            index=models.Index(
                fields=["engagement", "fact_key"], name="overlay_can_engagem_c6c874_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="canonicalfacts",
            unique_together={("engagement", "fact_key")},
        ),
    ]
