# Generated by Django 5.0.14 on 2025-11-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_overlay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellengagement",
            name="first_interaction_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of first interaction (set once, never updated)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wellengagement",
            name="interaction_count",
            field=models.IntegerField(
                default=0, help_text="Total number of interactions with this well"
            ),
        ),
        migrations.AddField(
            model_name="wellengagement",
            name="last_interaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("w3a_generated", "W3A Plan Generated"),
                    ("document_uploaded", "Document Uploaded"),
                    ("plan_modified", "Plan Modified"),
                    ("chat_created", "Chat Thread Created"),
                    ("advisory_requested", "Advisory Requested"),
                ],
                help_text="Type of the most recent interaction with this well",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wellengagement",
            name="metadata",
            field=models.JSONField(
                default=dict,
                help_text="Summary of interactions: plan_ids, document_ids, chat_thread_ids, counts, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="wellengagement",
            name="tenant_id",
            field=models.UUIDField(db_index=True),
        ),
    ]
