# Generated by Django 5.0.14 on 2025-11-02 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_overlay", "0002_wellengagement_first_interaction_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantGuardrailPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Tenant this policy applies to",
                        unique=True,
                    ),
                ),
                (
                    "risk_profile",
                    models.CharField(
                        choices=[
                            (
                                "conservative",
                                "Conservative - Strict limits, manual review required",
                            ),
                            (
                                "balanced",
                                "Balanced - Standard limits (platform default)",
                            ),
                            (
                                "aggressive",
                                "Aggressive - Relaxed limits, trust AI more",
                            ),
                            ("custom", "Custom - Manually configured"),
                        ],
                        default="balanced",
                        help_text="Predefined risk profile or custom configuration",
                        max_length=16,
                    ),
                ),
                (
                    "inherits_from_global",
                    models.BooleanField(
                        default=True,
                        help_text="If True, overlays on global baseline. If False, uses custom config.",
                    ),
                ),
                (
                    "allow_plan_changes",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch: can AI modify plans at all?",
                    ),
                ),
                (
                    "require_confirmation_above_risk",
                    models.FloatField(
                        default=0.5,
                        help_text="Auto-confirm only if risk < this value (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "max_material_delta_percent",
                    models.FloatField(
                        default=0.3,
                        help_text="Max material change as fraction (0.3 = 30%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "max_steps_removed",
                    models.IntegerField(
                        default=3,
                        help_text="Max number of steps AI can remove in one modification",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "allow_new_violations",
                    models.BooleanField(
                        default=False,
                        help_text="Can AI introduce new compliance violations?",
                    ),
                ),
                (
                    "allow_violations_with_precedent",
                    models.BooleanField(
                        default=False,
                        help_text="Allow violations if similar precedent exists with RRC approval",
                    ),
                ),
                (
                    "max_modifications_per_session",
                    models.IntegerField(
                        default=10,
                        help_text="Max modifications per chat session (per hour)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "allowed_operations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Whitelist of allowed operations. Empty = all allowed. Example: ['combine_plugs', 'adjust_interval']",
                    ),
                ),
                (
                    "blocked_operations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Blacklist of blocked operations. Example: ['replace_cibp']",
                    ),
                ),
                (
                    "district_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="District-specific policy overrides. Example: {'08A': {'max_material_delta_percent': 0.2}}",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this policy configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_guardrail_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Guardrail Policy",
                "verbose_name_plural": "Tenant Guardrail Policies",
                "db_table": "tenant_overlay_guardrail_policies",
            },
        ),
    ]
