# Generated by Django 5.0.14 on 2026-03-19 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public_core", "0025_plansnapshot_well_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("w3", "W-3"),
                            ("w3a", "W-3A"),
                            ("c103", "C-103"),
                            ("c104", "C-104"),
                            ("c105", "C-105"),
                        ],
                        max_length=10,
                    ),
                ),
                ("field_name", models.CharField(max_length=128)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("district", models.CharField(blank=True, max_length=10)),
                ("county", models.CharField(blank=True, max_length=64)),
                ("land_type", models.CharField(blank=True, max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("suggested_value", models.CharField(blank=True, max_length=255)),
                (
                    "trigger_condition",
                    models.JSONField(
                        default=dict,
                        help_text="JSON: {field_name, trigger_values, trigger_pattern, context_match}",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("cross_tenant", "Cross-Tenant Pattern"),
                            ("tenant", "Tenant-Specific"),
                            ("cold_start", "Cold-Start Rule"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("times_shown", models.IntegerField(default=0)),
                ("times_accepted", models.IntegerField(default=0)),
                ("times_dismissed", models.IntegerField(default=0)),
                ("acceptance_rate", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "intelligence_recommendations",
            },
        ),
        migrations.CreateModel(
            name="FilingStatusRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "filing_id",
                    models.CharField(
                        db_index=True,
                        help_text="Agency tracking/confirmation number",
                        max_length=128,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "agency",
                    models.CharField(
                        choices=[("RRC", "Texas RRC"), ("NMOCD", "New Mexico OCD")],
                        max_length=10,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("w3", "W-3"),
                            ("w3a", "W-3A"),
                            ("c103", "C-103"),
                            ("c104", "C-104"),
                            ("c105", "C-105"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                            ("deficiency", "Deficiency Notice"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("agency_remarks", models.TextField(blank=True)),
                ("reviewer_name", models.CharField(blank=True, max_length=128)),
                ("status_date", models.DateField(blank=True, null=True)),
                ("portal_url", models.URLField(blank=True)),
                ("raw_portal_data", models.JSONField(default=dict)),
                ("polled_at", models.DateTimeField(blank=True, null=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=2)),
                ("district", models.CharField(blank=True, max_length=10)),
                ("county", models.CharField(blank=True, max_length=64)),
                ("land_type", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "c103_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filing_statuses",
                        to="public_core.c103formorm",
                    ),
                ),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filing_statuses",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "w3_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filing_statuses",
                        to="public_core.w3formorm",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_statuses",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_filing_status",
            },
        ),
        migrations.CreateModel(
            name="PortalCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "agency",
                    models.CharField(
                        choices=[("RRC", "Texas RRC"), ("NMOCD", "New Mexico OCD")],
                        max_length=10,
                    ),
                ),
                ("encrypted_username", models.BinaryField()),
                ("encrypted_password", models.BinaryField()),
                ("last_successful_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "intelligence_portal_credentials",
                "unique_together": {("tenant_id", "agency")},
            },
        ),
        migrations.CreateModel(
            name="RecommendationInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("shown", "Shown"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                            ("snoozed", "Snoozed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("field_value_at_time", models.CharField(blank=True, max_length=255)),
                ("dismissal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="intelligence.recommendation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_recommendation_interactions",
            },
        ),
        migrations.CreateModel(
            name="RejectionPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("w3", "W-3"),
                            ("w3a", "W-3A"),
                            ("c103", "C-103"),
                            ("c104", "C-104"),
                            ("c105", "C-105"),
                        ],
                        max_length=10,
                    ),
                ),
                ("field_name", models.CharField(max_length=128)),
                ("issue_category", models.CharField(max_length=30)),
                ("issue_subcategory", models.CharField(blank=True, max_length=30)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("district", models.CharField(blank=True, max_length=10)),
                (
                    "agency",
                    models.CharField(
                        choices=[("RRC", "Texas RRC"), ("NMOCD", "New Mexico OCD")],
                        max_length=10,
                    ),
                ),
                ("pattern_description", models.TextField()),
                ("example_bad_value", models.CharField(blank=True, max_length=255)),
                ("example_good_value", models.CharField(blank=True, max_length=255)),
                ("occurrence_count", models.IntegerField(default=0)),
                ("tenant_count", models.IntegerField(default=0)),
                ("rejection_rate", models.FloatField(default=0.0)),
                ("first_observed", models.DateTimeField(blank=True, null=True)),
                ("last_observed", models.DateTimeField(blank=True, null=True)),
                ("is_trending", models.BooleanField(default=False)),
                (
                    "trend_direction",
                    models.FloatField(
                        default=0.0,
                        help_text="Slope: positive=increasing, negative=decreasing",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embedding_vector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejection_patterns",
                        to="public_core.documentvector",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_rejection_patterns",
            },
        ),
        migrations.AddField(
            model_name="recommendation",
            name="pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="intelligence.rejectionpattern",
            ),
        ),
        migrations.CreateModel(
            name="RejectionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=2)),
                ("district", models.CharField(blank=True, max_length=10)),
                ("county", models.CharField(blank=True, max_length=64)),
                ("land_type", models.CharField(blank=True, max_length=20)),
                (
                    "agency",
                    models.CharField(
                        choices=[("RRC", "Texas RRC"), ("NMOCD", "New Mexico OCD")],
                        max_length=10,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("w3", "W-3"),
                            ("w3a", "W-3A"),
                            ("c103", "C-103"),
                            ("c104", "C-104"),
                            ("c105", "C-105"),
                        ],
                        max_length=10,
                    ),
                ),
                ("raw_rejection_notes", models.TextField(blank=True)),
                ("rejection_date", models.DateField(blank=True, null=True)),
                ("reviewer_name", models.CharField(blank=True, max_length=128)),
                (
                    "parsed_issues",
                    models.JSONField(
                        default=list, help_text="AI-parsed list of field-level issues"
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsed", "AI Parsed"),
                            ("verified", "User Verified"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "submitted_form_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of form data at time of submission",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "c103_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejections",
                        to="public_core.c103formorm",
                    ),
                ),
                (
                    "filing_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejections",
                        to="intelligence.filingstatusrecord",
                    ),
                ),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejections",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "w3_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejections",
                        to="public_core.w3formorm",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejections",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "intelligence_rejection_records",
            },
        ),
        migrations.AddIndex(
            model_name="filingstatusrecord",
            index=models.Index(
                fields=["tenant_id", "-status_date"],
                name="intelligenc_tenant__a68c5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filingstatusrecord",
            index=models.Index(
                fields=["agency", "form_type", "status"],
                name="intelligenc_agency_f38538_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filingstatusrecord",
            index=models.Index(
                fields=["filing_id", "agency"], name="intelligenc_filing__68f24f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationinteraction",
            index=models.Index(
                fields=["recommendation", "-created_at"],
                name="intelligenc_recomme_154c53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationinteraction",
            index=models.Index(
                fields=["tenant_id", "action"], name="intelligenc_tenant__bccc6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionpattern",
            index=models.Index(
                fields=["form_type", "state"], name="intelligenc_form_ty_bd8ed9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionpattern",
            index=models.Index(
                fields=["is_trending"], name="intelligenc_is_tren_00e556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionpattern",
            index=models.Index(
                fields=["-occurrence_count"], name="intelligenc_occurre_a4b855_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rejectionpattern",
            unique_together={
                (
                    "form_type",
                    "field_name",
                    "issue_category",
                    "state",
                    "district",
                    "agency",
                )
            },
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["form_type", "field_name", "state"],
                name="intelligenc_form_ty_e9fca7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["scope", "is_active"], name="intelligenc_scope_28d002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["priority"], name="intelligenc_priorit_5763eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionrecord",
            index=models.Index(
                fields=["tenant_id", "-rejection_date"],
                name="intelligenc_tenant__82ad11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionrecord",
            index=models.Index(
                fields=["agency", "form_type"], name="intelligenc_agency_d3c1a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectionrecord",
            index=models.Index(
                fields=["parse_status"], name="intelligenc_parse_s_ab96b6_idx"
            ),
        ),
    ]
