from django.core.management.base import BaseCommand
from apps.policy_ingest.models import PolicyRule, PolicySection

class Command(BaseCommand):
    help = 'Create consolidated policy sections for rule 3.14'

    def handle(self, *args, **kwargs):
        # Fetch the rule object
        rule = PolicyRule.objects.get(rule_id='tx.tac.16.3.14')

        # Paths corresponding to sections a-k
        paths = list('abcdefghijk')

        # Full text from 3.14.txt
        full_text = '''
        (a) Definitions and application to plug. (1) The following words and terms, when used in this section, shall have the following meanings, unless the context clearly indicates otherwise:
        (A) Approved cementer--A cementing company, service company, or operator approved by the Commission or its delegate to mix and pump cement for the purpose of plugging a well in accordance with the provisions of this section. The term shall also apply to a cementing company, service company, or operator authorized by the Commission or its delegate to use an alternate material other than cement to plug a well.
        (B) Funnel viscosity--Viscosity as measured by the Marsh funnel, based on the number of seconds required for 1,000 cubic centimeters of fluid to flow through the funnel.
        (C) Groundwater conservation district--Any district or authority created under §52, Article III, or §59, Article XVI, Texas Constitution, that has the authority to regulate the spacing of water wells, the production from water wells, or both.
        (D) Operator designation form--A certificate of compliance and transportation authority or an application to drill, deepen, recomplete, plug back, or reenter that has been completed, signed, and filed with the Commission or its delegate.
        (E) Productive horizon--Any stratum known to contain oil, gas, or geothermal resources in producible quantities in the vicinity of an unplugged well.
        (F) Related piping--The surface piping and subsurface piping that is less than three feet beneath the ground surface between pieces of equipment located at any collection or treatment facility. Such piping would include piping between and among headers, manifolds, separators, storage tanks, gun barrels, heater treaters, dehydrators, and any other equipment located at a collection or treatment facility. The term is not intended to refer to lines, such as flowlines, gathering lines, and injection lines that lead up to and away from any such collection or treatment facility.
        (G) Reported production--Production of oil or gas, excluding production attributable to well tests, accurately reported to the Commission or its delegate on Form PR, Monthly Production Report.
        (H) Serve notice on the surface owner or resident--To hand deliver a written notice identifying the well or wells to be plugged and the projected date the well or wells will be plugged to the surface owner, or resident if the owner is absent, at least three days prior to the day of plugging or to mail the notice by first class mail, postage pre-paid, to the last known address of the surface owner or resident at least seven days prior to the day of plugging.
        (I) Usable quality water strata--All strata determined by the Groundwater Advisory Unit of the Oil and Gas Division to contain usable quality water.
        (J) Written notice--Notice actually received by the intended recipient in tangible or retrievable form, including notice set out on paper and hand-delivered, facsimile transmissions, and electronic mail transmissions.
        (2) The operator shall give the Commission notice of its intention to plug any well or wells drilled for oil, gas, or geothermal resources or for any other purpose over which the Commission has jurisdiction, except those specifically addressed in §3.100(e)(1 of this title (relating to Seismic Holes and Core Holes) (Statewide Rule 100), prior to plugging. The operator shall deliver or transmit the written notice to the district office on the appropriate form.
        (3) The operator shall cause the notice of its intention to plug to be delivered to the district office at least five days prior to the beginning of plugging operations. The notice shall set out the proposed plugging procedure as well as the complete casing record. The operator shall not commence the work of plugging the well or wells until the proposed procedure has been approved by the district director or the director's delegate. The operator shall not initiate approved plugging operations before the date set out in the notification for the beginning of plugging operations unless authorized by the district director or the director's delegate. The operator shall notify the district office at least four hours before commencing plugging operations and proceed with the work as approved. The district director or the director's delegate may grant exceptions to the requirements of this paragraph concerning the timing of notices when a workover or drilling rig is already at work on location, and ready to commence plugging operations. Operations shall not be suspended prior to plugging the well unless the hole is cased and casing is cemented in place in compliance with Commission rules. The Commission's approval of a notice of intent to plug and abandon a well shall not relieve an operator of the requirement to comply with subsection (b)(2) of this section, nor does such approval constitute an extension of time to comply with subsection (b)(2) of this section.
        (4) The surface owner and the operator may file an application to condition an abandoned well located on the surface owner's tract for usable quality water production operations. The application shall be made on Commission Form P-13, the Application of Landowner to Condition an Abandoned Well for Fresh Water Production.
        (A) Standard for Commission Approval. Before the Commission will consider approval of an application:
        (i) the surface owner shall assume responsibility for plugging the well and obligate himself, his heirs, successors, and assignees to complete the plugging operations;
        (ii) the operator responsible for plugging the well shall place all cement plugs required by this rule up to the base of the usable quality water strata; and
        (iii) the surface owner shall submit:
        (I) a signed statement attesting to the fact that:
        (-a-) there is no groundwater conservation district for the area in which the well is located; or
        (-b-) there is a groundwater conservation district for the area where the well is located, but the groundwater conservation district does not require that the well be permitted or registered; or
        (-c-) the surface owner has registered the well with the groundwater conservation district for the area where the well is located; or
        (II) a copy of the permit from the groundwater conservation district for the area where the well is located.
        (B) The duty of the operator to properly plug ends only when:
        (i) the operator has properly plugged the well in accordance with Commission requirements up to the base of the usable quality water stratum;
        (ii) the surface owner has registered the well with, or has obtained a permit for the well from, the groundwater conservation district, if applicable; and
        (iii) the Commission has approved the application of surface owner to condition an abandoned well for fresh water production.
        (5) The operator of a well shall serve notice on the surface owner of the well site tract, or the resident if the owner is absent, before the scheduled date for beginning the plugging operations. A representative of the surface owner may be present to witness the plugging of the well. Plugging shall not be delayed because of the lack of actual notice to the surface owner or resident if the operator has served notice as required by this paragraph. The district director or the director's delegate may grant exceptions to the requirements of this paragraph concerning the timing of notices when a workover or drilling rig is already at work on location and ready to commence plugging operations.
        (b) Commencement of plugging operations, extensions, and testing.
        (1) The operator shall complete and file in the district office a duly verified plugging record, in duplicate, on the appropriate form within 30 days after plugging operations are completed. A cementing report made by the party cementing the well shall be attached to, or made a part of, the plugging report. If the well the operator is plugging is a dry hole, an electric log status report shall be filed with the plugging record.
        (2) Plugging operations on each dry or inactive well shall be commenced within a period of one year after drilling or operations cease and shall proceed with due diligence until completed unless the Commission or its delegate approves a plugging extension under § 3.15 of this title (relating to Surface Equipment Removal Requirements and Inactive Wells).
        (3) The Commission may plug or replug any dry or inactive well as follows:
        (A) After notice and hearing, if the well is causing or is likely to cause the pollution of surface or subsurface water or if oil, gas, or other formation fluid is leaking from the well, and:
        (i) neither the operator nor any other entity responsible for plugging the well can be found; or
        (ii) neither the operator nor any other entity responsible for plugging the well has assets with which to plug the well.
        (B) Without a hearing if the well is a delinquent inactive well and:
        (i) the Commission has sent notice of its intention to plug the well as required by § 89.043(c of the Texas Natural Resources Code; and
        (ii) the operator did not request a hearing within the period (not less than 10 days after receipt) specified in the notice.
        (C) Without notice or hearing, if:
        (i) the Commission has issued a final order requiring that the operator plug the well and the order has not been complied with; or
        (ii) the well poses an immediate threat of pollution of surface or subsurface waters or of injury to the public health and the operator has failed to timely remediate the problem.
        (4) The Commission may seek reimbursement from the operator and any other entity responsible for plugging the well for state funds expended pursuant to paragraph (3) of this subsection.
        (c) Designated operator responsible for proper plugging.
        (1) The entity designated as the operator of a well specifically identified on the most recent Commission-approved operator designation form filed on or after September 1, 1997, is responsible for properly plugging the well in accordance with this section and all other applicable Commission rules and regulations concerning plugging of wells.
        (2) As to any well for which the most recent Commission-approved operator designation form was filed prior to September 1, 1997, the entity designated as operator on that form is presumed to be the entity responsible for the physical operation and control of the well and to be the entity responsible for properly plugging the well in accordance with this section and all other applicable Commission rules and regulations concerning plugging of wells. The presumption of responsibility may be rebutted only at a hearing called for the purpose of determining plugging responsibility.
        (d) General plugging requirements.
        (1) Wells shall be plugged to insure that all formations bearing usable quality water, oil, gas, or geothermal resources are protected. All cementing operations during plugging shall be performed under the direct supervision of the operator or his authorized representative, who shall not be an employee of the service or cementing company hired to plug the well. Direct supervision means supervision at the well site during the plugging operations. The operator and the cementer are both responsible for complying with the general plugging requirements of this subsection and for plugging the well in conformity with the procedure set forth in the approved notice of intention to plug and abandon for the well being plugged. The operator and cementer may each be assessed administrative penalties for failure to comply with the general plugging requirements of this subsection or for failure to plug the well in conformity with the approved notice of intention to plug and abandon the well.
        (2) Cement plugs shall be set to isolate each productive horizon and usable quality water strata. Plugs shall be set as necessary to separate multiple usable quality water strata by placing the required plug at each depth as determined by the Groundwater Advisory Unit of the Oil and Gas Division. The operator shall verify the placement of the plug required at the base of the deepest usable quality water stratum by tagging with tubing or drill pipe or by an alternate method approved by the district director or the district director's delegate.
        (3) Cement plugs shall be placed by the circulation or squeeze method through tubing or drill pipe. Cement plugs shall be placed by other methods only upon written request with the written approval of the district director or the director's delegate.
        (4) All cement for plugging shall be an approved API oil well cement without volume extenders and shall be mixed in accordance with API standards. Slurry weights shall be reported on the cementing report. The district director or the director's delegate may require that specific cement compositions be used in special situations; for example, when high temperature, salt section, or highly corrosive sections are present. An operator shall request approval to use alternate materials, other than API oil well cement without volume extenders, to plug a well by filing with the director or the director's delegate a written request providing all pertinent information to support the use of the proposed alternate material and plugging method. The director or the director's delegate shall determine whether such a request warrants approval, after considering factors which include but are not limited to whether or not the well to be plugged was used as an injection or disposal well; the well's history; the well's current bottom hole pressure; the presence of highly pressurized formations intersected by the wellbore; the method by which the alternative material will be placed in the wellbore; and the compressive strength and other performance specifications of the alternative material to be used. The director or the director's delegate shall approve such a request only if the proposed alternate material and plugging method will ensure that the well does not pose a potential threat of harm to natural resources.
        (5) Operators shall use only cementers approved by the director or the director's delegate, except when plugging is conducted in accordance with subparagraph (B)(ii) of this paragraph or paragraph (6) of this subsection. Cementing companies, service companies, or operators may apply for designation as approved cementers. Approval will be granted on a showing by the applicant of the ability to mix and pump cement or other alternate materials as approved by the director or the director's delegate in compliance with this rule. An approved cementer is authorized to conduct plugging operations in accordance with Commission rules in each Commission district.
        (A) A cementing company, service company, or operator seeking designation as an approved cementer shall file a request in writing with the district director of the district in which it proposes to conduct its initial plugging operations. The request shall contain the following information:
        (i) the name of the organization as shown on its most recent approved organizational report;
        (ii) a list of qualifications including personnel who will supervise mixing and pumping operations;
        (iii) length of time the organization has been in the business of cementing oil and gas wells;
        (iv) an inventory of the type of equipment to be used to mix and pump cement or other alternate materials as approved by the director or the director's delegate; and
        (v) a statement certifying that the organization will comply with all Commission rules.
        (B) No request for designation as an approved cementer will be approved until after the district director or the director's delegate has:
        (i) inspected all equipment to be used for mixing and pumping cement or other alternate materials as approved by the director or the director's delegate; and
        (ii) witnessed at least one plugging operation to determine if the cementing company, service company, or operator can properly mix and pump cement or other alternate materials as approved by the director or the director's delegate according to the specifications required by this rule.
        (C) The district director or the director's delegate shall file a letter with the director or the director's delegate recommending that the application to be designated as an approved cementer be approved or denied. If the district director or the director's delegate does not recommend approval, or the director or the director's delegate denies the application, the applicant may request a hearing on its application.
        (D) Designation as an approved cementer may be suspended or revoked for violations of Commission rules. The designation may be revoked or suspended administratively by the director or the director's delegate for violations of Commission rules if:
        (i) the cementer has been given written notice by personal service or by registered or certified mail informing the cementer of the proposed action, the facts or conduct alleged to warrant the proposed action, and of its right to request a hearing within 10 days to demonstrate compliance with Commission rules and all requirements for retention of designation as an approved cementer; and
        (ii) the cementer did not file a written request for a hearing within 10 days of receipt of the notice.
        (6) An operator may request administrative authority to plug its own wells without being an approved cementer. An operator seeking such authority shall file a written request with the district director and demonstrate its ability to mix and pump cement or other alternate materials as approved by the director or the director's delegate in compliance with this subsection. The district director or the director's delegate shall determine whether such a request warrants approval. If the district director or the director's delegate refuses to administratively approve this request, the operator may request a hearing on its request.
        (7) The district director or the director's delegate may require additional cement plugs to cover and contain any productive horizon or to separate any water stratum from any other water stratum if the water qualities or hydrostatic pressures differ sufficiently to justify separation. The tagging and/or pressure testing of any such plugs, or any other plugs, and respotting may be required if necessary to ensure that the well does not pose a potential threat of harm to natural resources.
        (8) For onshore or inland wells, a 10-foot cement plug shall be placed in the top of the well, and casing shall be cut off three feet below the ground surface.
        (9) Mud-laden fluid of at least 9-1/2 pounds per gallon with a minimum funnel viscosity of 40 seconds shall be placed in all portions of the well not filled with cement or other alternate material as approved by the director or the director's delegate. The hole shall be in static condition at the time the cement plugs are placed. The district director or the director's delegate may grant exceptions to the requirements of this paragraph if a deviation from the prescribed minimums for fluid weight or viscosity will insure that the well does not pose a potential threat of harm to natural resources. An operator shall request approval to use alternate fluid other than mud-laden fluid by filing with the district director a written request providing all pertinent information to support the use of the proposed alternate fluid. The district director or the director's delegate shall determine whether such a request warrants approval, and shall approve such a request only if the proposed alternate fluid will insure that the well does not pose a potential threat of harm to natural resources.
        (10) Non-drillable material that would hamper or prevent reentry of a well shall not be placed in any wellbore during plugging operations, except in the case of a well plugged and abandoned under the provisions of § 3.35 or §4.614(b of this title (relating to Procedures for Identification and Control of Wellbores in Which Certain Logging Tools Have Been Abandoned (Statewide Rule 35); and Authorized Disposal Methods, respectively). Pipe and unretrievable junk shall not be cemented in the hole during plugging operations without prior approval by the district director or the director's delegate.
        (11) All cement plugs, except the top plug, shall have sufficient slurry volume to fill 100 feet of hole, plus 10% for each 1,000 feet of depth from the ground surface to the bottom of the plug.
        (12) The operator shall fill the rathole, mouse hole, and cellar, and shall empty all tanks, vessels, related piping and flowlines that will not be actively used in the continuing operation of the lease within 120 days after plugging work is completed. Within the same 120 day period, the operator shall remove all such tanks, vessels, and related piping, remove all loose junk and trash from the location, and contour the location to discourage pooling of surface water at or around the facility site. The operator shall close all pits in accordance with the provisions of Chapter 4 of this title (relating to Environmental Protection), specifically Subchapter A (relating to Oil and Gas Waste Management) . The district director or the director's delegate may grant a reasonable extension of time of not more than an additional 120 days for the removal of tanks, vessels and related piping.
        (e) Plugging requirements for wells with surface casing.
        (1) When insufficient surface casing is set to protect all usable quality water strata and such usable quality water strata are exposed to the wellbore when production or intermediate casing is pulled from the well or as a result of such casing not being run, a cement plug shall be a minimum of 100 feet in length and shall extend at least 50 feet above and 50 feet below the base of the deepest usable quality water stratum. This plug shall be evidenced by tagging with tubing or drill pipe. The plug shall be respotted if it has not been properly placed. In addition, a cement plug shall be set across the shoe of the surface casing. This plug shall be a minimum of 100 feet in length and shall extend at least 50 feet above and below the shoe.
        (2) When sufficient surface casing has been set to protect all usable quality water strata, a cement plug shall be placed across the shoe of the surface casing. This plug shall be a minimum of 100 feet in length and shall extend at least 50 feet above the shoe and at least 50 feet below the shoe.
        (3) If surface casing has been set deeper than 200 feet below the base of the deepest usable quality water stratum, an additional cement plug shall be placed inside the surface casing across the base of the deepest usable quality water stratum. This plug shall be a minimum of 100 feet in length and shall extend at least 50 feet below and 50 feet above the base of the deepest usable quality water stratum.
        (4) Plugs shall be set as necessary to separate multiple usable quality water strata by placing the required plug at each depth as determined by the Groundwater Advisory Unit of the Oil and Gas Division.
        (5) An operator may not remove, cause to be removed, or allow to be removed surface casing from a well at abandonment. This prohibition applies to wells drilled by cable tool and rotary rigs alike.
        (f) Plugging requirements for wells with intermediate casing.
        (1) For wells in which the intermediate casing has been cemented through all usable quality water strata and all productive horizons, a cement plug meeting the requirements of subsection (d)(11) of this section shall be placed inside the casing and centered opposite the base of the deepest usable quality water stratum, but extend no less than 50 feet above and below the base of the deepest usable quality water stratum.
        (2) For wells in which intermediate casing is not cemented through all usable quality water strata and all productive horizons, and if the casing will not be pulled, the intermediate casing shall be perforated at the required depths to place cement outside of the casing by squeeze cementing through casing perforations.
        (3) Additionally, plugs shall be set as necessary to separate multiple usable quality water strata by placing the required plug at each depth as determined by the Groundwater Advisory Unit of the Oil and Gas Division.
        (g) Plugging requirements for wells with production casing.
        (1) For wells in which the production casing has been cemented through all usable quality water strata and all productive horizons, a cement plug meeting the requirements of subsection (d)(11) of this section shall be placed inside the casing and centered opposite the base of the deepest usable quality water stratum and across any multi-stage cementing tool. This plug shall be a minimum of 100 feet in length and shall extend at least 50 feet below and 50 feet above the base of the deepest usable quality water stratum.
        (2) For wells in which the production casing has not been cemented through all usable quality water strata and all productive horizons and if the casing will not be pulled, the production casing shall be perforated at the required depths to place cement outside of the casing by squeeze cementing through casing perforations.
        (3) The district director or the director's delegate may approve a cast iron bridge plug to be placed immediately above each perforated interval, provided at least 20 feet of cement is placed on top of each bridge plug. A bridge plug shall not be set in any well at a depth where the pressure or temperature exceeds the ratings recommended by the bridge plug manufacturer.
        (4) Additionally, plugs shall be set as necessary to separate multiple usable quality water strata by placing the required plug at each depth as determined by the Groundwater Advisory Unit of the Oil and Gas Division.
        (h) Plugging requirements for well with screen or liner.
        (1) If practical, the screen or liner shall be removed from the well.
        (2) If the screen or liner is not removed, a cement plug in accordance with subsection (d)(11) of this section shall be placed at the top of the screen or liner.
        (i) Plugging requirements for wells without production casing and open-hole completions.
        (1) Any productive horizon or any formation in which a pressure or formation water problem is known to exist shall be isolated by cement plugs centered at the top and bottom of the formation. Each cement plug shall have sufficient slurry volume to fill a calculated height as specified in subsection (d)(11) of this section.
        (2) If the gross thickness of any such formation is less than 100 feet, the tubing or drill pipe shall be suspended 50 feet below the base of the formation. Sufficient slurry volume shall be pumped to fill the calculated height from the bottom of the tubing or drill pipe up to a point at least 50 feet above the top of the formation, plus 10% for each 1,000 feet of depth from the ground surface to the bottom of the plug.
        (j) The district director or the director's delegate shall review and approve the notification of intention to plug in a manner so as to accomplish the purposes of this section. The district director or the director's delegate may approve, modify, or reject the operator's notification of intention to plug. If the proposal is modified or rejected, the operator may request a review by the director or the director's delegate. If the proposal is not administratively approved, the operator may request a hearing on the matter. After hearing, the examiner shall recommend final action by the Commission.
        (k) Plugging horizontal drainhole wells. All plugs in horizontal drainhole wells shall be set in accordance with subsection (d)(11) of this section. The productive horizon isolation plug shall be set from a depth 50 feet below the top of the productive horizon to a depth either 50 feet above the top of the productive horizon, or 50 feet above the production casing shoe if the production casing is set above the top of the productive horizon. If the production casing shoe is set below the top of the productive horizon, then the productive horizon isolation plug shall be set from a depth 50 feet below the production casing shoe to a depth that is 50 feet above the top of the productive horizon. In accordance with subsection (d)(7) of this section, the Commission or its delegate may require additional plugs.
        ''' # Ensure the content is fully pasted here.

        # Split the text by sections and create entries
        previous_text = full_text
        for path in paths:
            divided_text = previous_text.split(f'({path})', 1)
            if len(divided_text) < 2:
                break
            _, sec_text = divided_text
            full_section = sec_text.split(f'({chr(ord(path) + 1)})', 1)[0] if path != 'k' else sec_text
            PolicySection.objects.create(rule=rule, path=path, text=full_section.strip(), version_tag='')
            previous_text = sec_text
            self.stdout.write(self.style.SUCCESS(f'Section created for {path}'))
