from django.core.management.base import BaseCommand
from apps.policy_ingest.models import PolicyRule

class Command(BaseCommand):
    help = 'Update policy rule titles with provided mappings.'

    def handle(self, *args, **options):
        # Mapping of rule IDs to titles
        rule_titles = {
            'tx.tac.16.3.1': 'Organization Report; Retention of Records; Notice Requirements',
            'tx.tac.16.3.2': 'Commission Access to Properties',
            'tx.tac.16.3.3': 'Identification of Properties, Wells, and Tanks',
            'tx.tac.16.3.4': 'Oil and Geothermal Lease Numbers and Gas Well ID Numbers Required on All Forms',
            'tx.tac.16.3.5': 'Application To Drill, Deepen, Reenter, or Plug Back',
            'tx.tac.16.3.6': 'Application for Multiple Completion',
            'tx.tac.16.3.7': 'Strata To Be Sealed Off',
            'tx.tac.16.3.8': '[Effective until 7/1/2025] Water Protection',
            'tx.tac.16.3.8v2': '[Effective 7/1/2025] Water Protection, version 2',
            'tx.tac.16.3.9': 'Disposal Wells',
            'tx.tac.16.3.10': 'Restriction of Production of Oil and Gas from Different Strata',
            'tx.tac.16.3.11': 'Inclination and Directional Surveys Required',
            'tx.tac.16.3.12': 'Directional Survey Company Report',
            'tx.tac.16.3.13': 'Casing, Cementing, Drilling, Well Control, and Completion Requirements',
            'tx.tac.16.3.14': '[Effective until 7/1/2025] Plugging',
            'tx.tac.16.3.14v2': '[Effective 7/1/2025] Plugging, version 2',
            'tx.tac.16.3.15': 'Surface Equipment Removal Requirements and Inactive Wells',
            'tx.tac.16.3.16': 'Log and Completion or Plugging Report',
            'tx.tac.16.3.17': 'Pressure on Bradenhead',
            'tx.tac.16.3.18': 'Mud Circulation Required',
            'tx.tac.16.3.19': 'Density of Mud - Fluid',
            'tx.tac.16.3.20': 'Notification of Fire Breaks, Leaks, or Blow-Outs',
            'tx.tac.16.3.21': 'Fire Prevention and Swabbing',
            'tx.tac.16.3.22': '[Effective until 7/1/2025] Protection of Birds',
            'tx.tac.16.3.22v2': '[Effective 7/1/2025] Protection of Birds, version 2',
            'tx.tac.16.3.23': 'Vacuum Pumps',
            'tx.tac.16.3.24': 'Check Valves Required',
            'tx.tac.16.3.25': 'Use of Common Storage',
            'tx.tac.16.3.26': 'Separating Devices, Tanks, and Surface Commingling of Oil',
            'tx.tac.16.3.27': 'Gas to Be Measured and Surface Commingling of Gas',
            'tx.tac.16.3.28': 'Potential and Deliverability of Gas Wells to be Ascertained and Reported',
            'tx.tac.16.3.29': 'Hydraulic Fracturing Chemical Disclosure Requirements',
            'tx.tac.16.3.30': '[Effective until 7/1/2025] Memorandum of Understanding between the Railroad Commission of Texas (RRC) and the Texas Commission on Environmental Quality (TCEQ)',
            'tx.tac.16.3.30v2': '[Effective 7/1/2025] Memorandum of Understanding between the Railroad Commission of Texas (RRC) and the Texas Commission on Environmental Quality (TCEQ), version 2',
            'tx.tac.16.3.31': 'Gas Reservoirs and Gas Well Allowable',
            'tx.tac.16.3.32': 'Gas Well Gas and Casinghead Gas Shall Be Utilized for Legal Purposes',
            'tx.tac.16.3.33': 'Geothermal Resource Production Test Forms Required',
            'tx.tac.16.3.34': 'Gas To Be Produced and Purchased Ratably',
            'tx.tac.16.3.35': 'Procedures for Identification and Control of Wellbores in Which Certain Logging Tools Have Been Abandoned',
            'tx.tac.16.3.36': 'Oil, Gas, Brine, or Geothermal Resource Operation in Hydrogen Sulfide Areas',
            'tx.tac.16.3.37': 'Statewide Spacing Rule',
            'tx.tac.16.3.38': 'Well Densities',
            'tx.tac.16.3.39': 'Proration and Drilling Units: Contiguity of Acreage and Exception Thereto',
            'tx.tac.16.3.40': 'Assignment of Acreage to Pooled Development and Proration Units',
            'tx.tac.16.3.41': 'Application for New Oil or Gas Field Designation and/or Allowable',
            'tx.tac.16.3.42': 'Oil Discovery Allowable',
            'tx.tac.16.3.43': 'Application for Temporary Field Rules',
            'tx.tac.16.3.45': 'Oil Allowables',
            'tx.tac.16.3.46': 'Fluid Injection into Productive Reservoirs',
            'tx.tac.16.3.47': 'Allowable Transfers for Saltwater Injection Wells',
            'tx.tac.16.3.48': 'Capacity Oil Allowables for Secondary or Tertiary Recovery Projects',
            'tx.tac.16.3.49': 'Gas-Oil Ratio',
            'tx.tac.16.3.50': 'Enhanced Oil Recovery Projects - Approval and Certification for Tax Incentive',
            'tx.tac.16.3.51': 'Oil Potential Test Forms Required',
            'tx.tac.16.3.52': 'Oil Well Allowable Production',
            'tx.tac.16.3.53': 'Annual Well Tests and Well Status Reports Required',
            'tx.tac.16.3.54': 'Gas Reports Required',
            'tx.tac.16.3.55': 'Reports on Gas Wells Commingling Liquid Hydrocarbons before Metering',
            'tx.tac.16.3.56': 'Scrubber Oil and Skim Hydrocarbons',
            'tx.tac.16.3.57': '[Effective until 7/1/2025] Reclaiming Tank Bottoms, Other Hydrocarbon Wastes, and Other Waste Materials',
            'tx.tac.16.3.57v2': '[Effective 7/1/2025] Reclaiming Tank Bottoms, Other Hydrocarbon Wastes, and Other Waste Materials, version 2',
            'tx.tac.16.3.58': 'Certificate of Compliance and Transportation Authority; Operator Reports',
            'tx.tac.16.3.59': 'Oil and Gas Transporter\'s Reports',
            'tx.tac.16.3.60': 'Refinery Reports',
            'tx.tac.16.3.61': 'Definitions',
            'tx.tac.16.3.62': 'Prerequisites to Suit',
            'tx.tac.16.3.63': 'Sovereign Immunity',
            'tx.tac.16.3.65': 'Critical Designation of Natural Gas Infrastructure',
            'tx.tac.16.3.66': 'Weather Emergency Preparedness Standards',
            'tx.tac.16.3.70': 'Pipeline Permits Required',
            'tx.tac.16.3.71': 'Costs of Negotiation',
            'tx.tac.16.3.72': 'Request for Contested Case Hearing',
            'tx.tac.16.3.73': 'Pipeline Connection; Cancellation of Certificate of Compliance; Severance',
            'tx.tac.16.3.76': 'Costs of Mediation',
            'tx.tac.16.3.78': 'Fees and Financial Security Requirements',
            'tx.tac.16.3.79': 'Definitions',
            'tx.tac.16.3.80': 'Commission Oil and Gas Forms, Applications, and Filing Requirements',
            'tx.tac.16.3.81': 'Class III Brine Mining Injection Wells',
            'tx.tac.16.3.82': 'Brine Production Projects and Associated Brine Production Wells and Class V Spent Brine Return Injection Wells',
            'tx.tac.16.3.83': 'Tax Exemption for Two-Year Inactive Wells and Three-Year Inactive Wells',
            'tx.tac.16.3.84': 'Gas Shortage Emergency Response',
            'tx.tac.16.3.85': 'Manifest To Accompany Each Transport of Liquid Hydrocarbons by Vehicle',
            'tx.tac.16.3.86': 'Horizontal Drainhole Wells',
            'tx.tac.16.3.91': '[Effective until 7/1/2025] Cleanup of Soil Contaminated by a Crude Oil Spill',
            'tx.tac.16.3.91v2': '[Effective 7/1/2025] Cleanup of Soil Contaminated by a Crude Oil Spill, version 2',
            'tx.tac.16.3.93': 'Water Quality Certification Definitions',
            'tx.tac.16.3.95': 'Underground Storage of Liquid or Liquefied Hydrocarbons in Salt Formations',
            'tx.tac.16.3.96': 'Underground Storage of Gas in Productive or Depleted Reservoirs',
            'tx.tac.16.3.97': 'Underground Storage of Gas in Salt Formations',
            'tx.tac.16.3.98': '[Effective until 7/1/2025] Standards for Management of Hazardous Oil and Gas Waste',
            'tx.tac.16.3.98v2': '[Effective 7/1/2025] Standards for Management of Hazardous Oil and Gas Waste, version 2',
            'tx.tac.16.3.99': 'Cathodic Protection Wells',
            'tx.tac.16.3.100': 'Seismic Holes and Core Holes',
            'tx.tac.16.3.101': 'Certification for Severance Tax Exemption or Reduction for Gas Produced From High-Cost Gas Wells',
            'tx.tac.16.3.102': 'Tax Reduction for Incremental Production',
            'tx.tac.16.3.103': 'Certification for Severance Tax Exemption for Casinghead Gas Previously Vented or Flared',
            'tx.tac.16.3.106': 'Sour Gas Pipeline Facility Construction Permit',
            'tx.tac.16.3.107': 'Penalty Guidelines for Oil and Gas Violations',
        }

        for rule_id, title in rule_titles.items():
            rule = PolicyRule.objects.filter(rule_id=rule_id).first()
            if rule:
                rule.title = title
                rule.save()
                self.stdout.write(self.style.SUCCESS(f"Updated title for {rule_id}: {title}"))
            else:
                self.stdout.write(self.style.WARNING(f"No rule found for {rule_id}"))

