# Generated by Django 5.0.14 on 2025-11-01 17:43

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api14", models.CharField(max_length=14, unique=True)),
                ("state", models.CharField(max_length=2)),
                ("county", models.CharField(blank=True, max_length=64)),
                ("operator_name", models.CharField(blank=True, max_length=128)),
                ("field_name", models.CharField(blank=True, max_length=128)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "public_core_well_registry",
                "indexes": [
                    models.Index(fields=["api14"], name="public_core_api14_649b7b_idx"),
                    models.Index(
                        fields=["state", "county"], name="public_core_state_a2c9e1_idx"
                    ),
                    models.Index(
                        fields=["operator_name"], name="public_core_operato_c22994_idx"
                    ),
                    models.Index(
                        fields=["field_name"], name="public_core_field_n_70069c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicWellDepths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "td_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "kb_elev_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "gl_elev_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "surf_shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "int_shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "prod_shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_depths",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_well_depths",
            },
        ),
        migrations.CreateModel(
            name="PublicPerforation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_ft", models.DecimalField(decimal_places=2, max_digits=8)),
                ("bottom_ft", models.DecimalField(decimal_places=2, max_digits=8)),
                ("formation", models.CharField(blank=True, max_length=128)),
                (
                    "shot_density_spf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "phase_deg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_perforations",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_perforation",
                "indexes": [
                    models.Index(
                        fields=["well", "top_ft", "bottom_ft"],
                        name="public_core_well_id_f51729_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_key", models.CharField(max_length=128)),
                ("value", models.JSONField()),
                ("units", models.CharField(blank=True, max_length=32)),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_facts",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_facts",
                "indexes": [
                    models.Index(
                        fields=["well", "fact_key"],
                        name="public_core_well_id_08edae_idx",
                    )
                ],
                "unique_together": {("well", "fact_key")},
            },
        ),
        migrations.CreateModel(
            name="PublicCasingString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "string_no",
                    models.PositiveIntegerField(
                        help_text="Ordinal number from surface downward (1=surface)"
                    ),
                ),
                ("outside_dia_in", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "weight_ppf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=32)),
                ("thread_type", models.CharField(blank=True, max_length=64)),
                (
                    "top_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cement_to_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_casing_strings",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_casing_string",
                "indexes": [
                    models.Index(
                        fields=["well", "string_no"],
                        name="public_core_well_id_3d247a_idx",
                    ),
                    models.Index(
                        fields=["well"], name="public_core_well_id_572d10_idx"
                    ),
                ],
                "unique_together": {("well", "string_no")},
            },
        ),
        migrations.CreateModel(
            name="PublicArtifacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("url", models.URLField(max_length=1024)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_artifacts",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_artifacts",
                "indexes": [
                    models.Index(
                        fields=["well", "kind"], name="public_core_well_id_ebcc18_idx"
                    ),
                    models.Index(
                        fields=["sha256"], name="public_core_sha256_23547b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_id", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("baseline", "baseline"),
                            ("post_edit", "post_edit"),
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                ("kernel_version", models.CharField(blank=True, max_length=32)),
                ("overlay_id", models.CharField(blank=True, max_length=128)),
                ("policy_id", models.CharField(blank=True, max_length=64)),
                ("extraction_meta", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_snapshots",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_plan_snapshots",
                "indexes": [
                    models.Index(
                        fields=["well", "plan_id", "kind"],
                        name="public_core_well_id_333c78_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="public_core_created_db24a2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtractedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_number", models.CharField(db_index=True, max_length=16)),
                ("document_type", models.CharField(db_index=True, max_length=64)),
                ("source_path", models.TextField(blank=True)),
                ("model_tag", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="success", max_length=32)),
                ("errors", models.JSONField(default=list)),
                ("json_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_documents",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_extracted_documents",
                "indexes": [
                    models.Index(
                        fields=["api_number", "document_type"],
                        name="public_core_api_num_313635_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="public_core_created_026346_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentVector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("document_type", models.CharField(db_index=True, max_length=50)),
                ("section_name", models.CharField(db_index=True, max_length=255)),
                ("section_text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_vectors",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_document_vectors",
                "indexes": [
                    models.Index(
                        fields=["well", "document_type"],
                        name="public_core_well_id_a1c1cf_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="public_core_created_bb7017_idx"
                    ),
                ],
            },
        ),
    ]
