# Generated by Django 5.0.14 on 2025-10-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api14", models.CharField(max_length=14, unique=True)),
                ("state", models.CharField(max_length=2)),
                ("county", models.CharField(blank=True, max_length=64)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "public_core_well_registry",
                "indexes": [
                    models.Index(fields=["api14"], name="public_core_api14_649b7b_idx"),
                    models.Index(
                        fields=["state", "county"], name="public_core_state_a2c9e1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_key", models.CharField(max_length=128)),
                ("value", models.JSONField()),
                ("units", models.CharField(blank=True, max_length=32)),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_facts",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_facts",
                "indexes": [
                    models.Index(
                        fields=["well", "fact_key"],
                        name="public_core_well_id_08edae_idx",
                    )
                ],
                "unique_together": {("well", "fact_key")},
            },
        ),
        migrations.CreateModel(
            name="PublicArtifacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("url", models.URLField(max_length=1024)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_artifacts",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_artifacts",
                "indexes": [
                    models.Index(
                        fields=["well", "kind"], name="public_core_well_id_ebcc18_idx"
                    ),
                    models.Index(
                        fields=["sha256"], name="public_core_sha256_23547b_idx"
                    ),
                ],
            },
        ),
    ]
