# Generated by Django 5.0.14 on 2025-10-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicWellDepths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "td_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "kb_elev_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "gl_elev_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "surf_shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "int_shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "prod_shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_depths",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_well_depths",
            },
        ),
        migrations.CreateModel(
            name="PublicCasingString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "string_no",
                    models.PositiveIntegerField(
                        help_text="Ordinal number from surface downward (1=surface)"
                    ),
                ),
                ("outside_dia_in", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "weight_ppf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=32)),
                ("thread_type", models.CharField(blank=True, max_length=64)),
                (
                    "top_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "shoe_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cement_to_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_casing_strings",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_casing_string",
                "indexes": [
                    models.Index(
                        fields=["well", "string_no"],
                        name="public_core_well_id_3d247a_idx",
                    ),
                    models.Index(
                        fields=["well"], name="public_core_well_id_572d10_idx"
                    ),
                ],
                "unique_together": {("well", "string_no")},
            },
        ),
        migrations.CreateModel(
            name="PublicPerforation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_ft", models.DecimalField(decimal_places=2, max_digits=8)),
                ("bottom_ft", models.DecimalField(decimal_places=2, max_digits=8)),
                ("formation", models.CharField(blank=True, max_length=128)),
                (
                    "shot_density_spf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "phase_deg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("provenance", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, max_length=256)),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_perforations",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_public_perforation",
                "indexes": [
                    models.Index(
                        fields=["well", "top_ft", "bottom_ft"],
                        name="public_core_well_id_f51729_idx",
                    )
                ],
            },
        ),
    ]
