# Generated by Django 5.0.14 on 2025-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansnapshot",
            name="tenant_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Tenant who created this snapshot (null for RRC-baseline plans)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plansnapshot",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - Shareable for learning"),
                    ("private", "Private - Tenant-only"),
                ],
                db_index=True,
                default="private",
                help_text="Public: baseline/approved plans (shareable). Private: work-in-progress (tenant-only).",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="plansnapshot",
            index=models.Index(
                fields=["tenant_id", "visibility"],
                name="public_core_tenant__b5599f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plansnapshot",
            index=models.Index(
                fields=["visibility", "kind"], name="public_core_visibil_1d9083_idx"
            ),
        ),
    ]
