# Generated by Django 5.0.14 on 2025-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0002_plansnapshot_tenant_id_plansnapshot_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddocument",
            name="is_validated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Passed security scan and API verification (W2/W15/GAU/W3/W3A tenant uploads become public when validated)",
            ),
        ),
        migrations.AddField(
            model_name="extracteddocument",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("rrc", "RRC - Public Regulator Data"),
                    ("tenant_upload", "Tenant Upload - User Provided"),
                ],
                db_index=True,
                default="rrc",
                help_text="Origin of document: RRC public data or tenant upload",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="extracteddocument",
            name="uploaded_by_tenant",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Tenant who uploaded this file (null for RRC-sourced documents)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extracteddocument",
            name="validation_errors",
            field=models.JSONField(
                default=list,
                help_text="List of validation failure reasons (security scan failures, API mismatches, etc.)",
            ),
        ),
        migrations.AddIndex(
            model_name="extracteddocument",
            index=models.Index(
                fields=["uploaded_by_tenant", "source_type"],
                name="public_core_uploade_8ec6d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="extracteddocument",
            index=models.Index(
                fields=["is_validated", "document_type"],
                name="public_core_is_vali_558e28_idx",
            ),
        ),
    ]
