# Generated by Django 5.0.14 on 2025-11-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0003_extracteddocument_is_validated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellregistry",
            name="lease_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="wellregistry",
            name="well_number",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
