# Generated by Django 5.0.14 on 2025-11-02 04:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0004_wellregistry_lease_name_wellregistry_well_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plansnapshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft - Initial plan generation"),
                    ("internal_review", "Internal Review - Being modified"),
                    ("engineer_approved", "Engineer Approved - Ready to file"),
                    ("filed", "Filed - Submitted to RRC"),
                    ("under_agency_review", "Under Agency Review - RRC reviewing"),
                    ("agency_approved", "Agency Approved - RRC approved"),
                    ("agency_rejected", "Agency Rejected - RRC rejected"),
                    (
                        "revision_requested",
                        "Revision Requested - RRC requested changes",
                    ),
                    ("withdrawn", "Withdrawn - Filing withdrawn"),
                ],
                db_index=True,
                default="draft",
                help_text="Current workflow status of the plan",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPlanSnapshot",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("plan_id", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("baseline", "baseline"),
                            ("post_edit", "post_edit"),
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                ("kernel_version", models.CharField(blank=True, max_length=32)),
                ("overlay_id", models.CharField(blank=True, max_length=128)),
                ("policy_id", models.CharField(blank=True, max_length=64)),
                ("extraction_meta", models.JSONField(default=dict)),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant who created this snapshot (null for RRC-baseline plans)",
                        null=True,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Shareable for learning"),
                            ("private", "Private - Tenant-only"),
                        ],
                        db_index=True,
                        default="private",
                        help_text="Public: baseline/approved plans (shareable). Private: work-in-progress (tenant-only).",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft - Initial plan generation"),
                            ("internal_review", "Internal Review - Being modified"),
                            ("engineer_approved", "Engineer Approved - Ready to file"),
                            ("filed", "Filed - Submitted to RRC"),
                            (
                                "under_agency_review",
                                "Under Agency Review - RRC reviewing",
                            ),
                            ("agency_approved", "Agency Approved - RRC approved"),
                            ("agency_rejected", "Agency Rejected - RRC rejected"),
                            (
                                "revision_requested",
                                "Revision Requested - RRC requested changes",
                            ),
                            ("withdrawn", "Withdrawn - Filing withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current workflow status of the plan",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical plan snapshot",
                "verbose_name_plural": "historical plan snapshots",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
