# Generated by Django 5.0.14 on 2025-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0005_plansnapshot_status_historicalplansnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellregistry",
            name="district",
            field=models.CharField(
                blank=True, help_text="RRC District (e.g., '8A', '7C')", max_length=8
            ),
        ),
        migrations.AddIndex(
            model_name="wellregistry",
            index=models.Index(
                fields=["district"], name="public_core_distric_6c5fd6_idx"
            ),
        ),
    ]
