# Generated by Django 5.0.14 on 2025-12-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0008_extracteddocument_tracking_no"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="extracteddocument",
            new_name="public_core_api_num_e31a65_idx",
            old_name="public_core_api_numb_document_tracking_idx",
        ),
        migrations.RenameIndex(
            model_name="extracteddocument",
            new_name="public_core_trackin_a6c2a1_idx",
            old_name="public_core_tracking_no_document_idx",
        ),
        migrations.RenameIndex(
            model_name="w3eventorm",
            new_name="public_core_api_num_ec15b0_idx",
            old_name="public_core_api_numb_idx1",
        ),
        migrations.RenameIndex(
            model_name="w3eventorm",
            new_name="public_core_well_id_f87626_idx",
            old_name="public_core_well_id_idx1",
        ),
        migrations.RenameIndex(
            model_name="w3formorm",
            new_name="public_core_api_num_21de12_idx",
            old_name="public_core_api_numb_idx3",
        ),
        migrations.RenameIndex(
            model_name="w3formorm",
            new_name="public_core_well_id_02300e_idx",
            old_name="public_core_well_id_idx3",
        ),
        migrations.RenameIndex(
            model_name="w3plugorm",
            new_name="public_core_api_num_ca15bd_idx",
            old_name="public_core_api_numb_idx2",
        ),
        migrations.RenameIndex(
            model_name="w3plugorm",
            new_name="public_core_well_id_06b54e_idx",
            old_name="public_core_well_id_idx2",
        ),
    ]
