# Generated by Django 5.0.14 on 2026-01-08 06:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public_core",
            "0009_rename_public_core_api_numb_document_tracking_idx_public_core_api_num_e31a65_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalW3FormORM",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("api_number", models.CharField(db_index=True, max_length=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to RRC"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        help_text="Complete W-3 form JSON (header, plugs, casing_record, perforations, duqw, remarks)"
                    ),
                ),
                (
                    "well_geometry",
                    models.JSONField(
                        default=dict,
                        help_text="Casing record, existing tools, retainer tools, historic cement, KOP",
                    ),
                ),
                (
                    "rrc_export",
                    models.JSONField(
                        default=list,
                        help_text="Array of plug rows formatted for RRC submission",
                    ),
                ),
                ("validation_warnings", models.JSONField(default=list)),
                ("validation_errors", models.JSONField(default=list)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rrc_confirmation_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "generated_from_w3a_snapshot",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of W-3A plan snapshot used to generate this form",
                        null=True,
                    ),
                ),
                (
                    "auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if W-3A was auto-generated from RRC data",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical w3 form orm",
                "verbose_name_plural": "historical w3 form orms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WellEditAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_path",
                    models.CharField(
                        help_text="JSON dotpath to edited field (e.g., 'casing_record.0.cement_top_ft')",
                        max_length=255,
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable field name (e.g., 'Production Casing TOC')",
                        max_length=128,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("extraction", "Extraction - Raw document data edit"),
                            ("geometry", "Geometry - Derived well geometry edit"),
                            ("plan", "Plan - Plan-only edit (not applied to registry)"),
                        ],
                        default="extraction",
                        help_text="Where this edit was made (extraction, geometry, or plan)",
                        max_length=16,
                    ),
                ),
                (
                    "original_value",
                    models.JSONField(
                        blank=True,
                        help_text="Original extracted value (null if field was missing)",
                        null=True,
                    ),
                ),
                (
                    "edited_value",
                    models.JSONField(help_text="User-provided edited value"),
                ),
                (
                    "editor_display_name",
                    models.CharField(
                        help_text="Display name at time of edit (for audit trail)",
                        max_length=128,
                    ),
                ),
                (
                    "editor_tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID of editor (for filtering cross-tenant visibility)",
                        null=True,
                    ),
                ),
                (
                    "edit_reason",
                    models.TextField(
                        blank=True, help_text="User-provided reason for the edit"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not yet applied to WellRegistry"),
                            ("applied", "Applied - Written to WellRegistry"),
                            ("rejected", "Rejected - User declined to apply"),
                            ("superseded", "Superseded - Replaced by newer edit"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current stage of this edit",
                        max_length=16,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this edit was applied to WellRegistry",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who applied this edit to WellRegistry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_well_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the edit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="well_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        help_text="Plan snapshot this edit is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        help_text="Well this edit applies to (null for plan-only edits)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_audits",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_well_edit_audits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["plan_snapshot", "stage"],
                        name="public_core_plan_sn_f65c5d_idx",
                    ),
                    models.Index(
                        fields=["well", "stage"], name="public_core_well_id_4f30e7_idx"
                    ),
                    models.Index(
                        fields=["editor_tenant_id", "stage"],
                        name="public_core_editor__340571_idx",
                    ),
                    models.Index(
                        fields=["context", "stage"],
                        name="public_core_context_69d1f4_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="public_core_created_7a11f8_idx"
                    ),
                ],
            },
        ),
    ]
