# Generated by Django 5.0.14 on 2026-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0010_historicalw3formorm_welleditaudit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="extracteddocument",
            index=models.Index(
                fields=["api_number", "source_path", "document_type", "status"],
                name="public_core_api_num_685bef_idx",
            ),
        ),
    ]
