# Generated by Django 5.0.14 on 2026-02-10 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0012_bulkjob"),
        ("tenants", "0006_clientworkspace_usagerecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField(blank=True)),
                ("is_automated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "public_core_plan_approvals",
                "ordering": ["-approved_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="bulkjob",
            new_name="public_core_tenant__a4b697_idx",
            old_name="public_core_tenant__7b5cfa_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkjob",
            new_name="public_core_tenant__a9b4b8_idx",
            old_name="public_core_tenant__19e3a5_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkjob",
            new_name="public_core_job_typ_d2799f_idx",
            old_name="public_core_job_typ_8d4e51_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkjob",
            new_name="public_core_celery__c2060e_idx",
            old_name="public_core_celery__f2b8c0_idx",
        ),
        migrations.AddField(
            model_name="wellregistry",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Client workspace this well belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wells",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddIndex(
            model_name="wellregistry",
            index=models.Index(
                fields=["workspace"], name="public_core_workspa_53dbbc_idx"
            ),
        ),
        migrations.AddField(
            model_name="planapproval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="planapproval",
            name="plan_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="public_core.plansnapshot",
            ),
        ),
    ]
