# Generated by Django 5.0.14 on 2026-02-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0013_planapproval_and_more"),
        ("tenants", "0006_clientworkspace_usagerecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalplansnapshot",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Workspace this plan belongs to (null = visible in all workspaces)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddField(
            model_name="historicalw3formorm",
            name="tenant_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalw3formorm",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddField(
            model_name="plansnapshot",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this plan belongs to (null = visible in all workspaces)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_snapshots",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddField(
            model_name="w3formorm",
            name="tenant_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="w3formorm",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="w3_forms",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddIndex(
            model_name="plansnapshot",
            index=models.Index(
                fields=["workspace"], name="public_core_workspa_727dba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plansnapshot",
            index=models.Index(
                fields=["tenant_id", "workspace"], name="public_core_tenant__cb23cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="w3formorm",
            index=models.Index(
                fields=["tenant_id"], name="public_core_tenant__6d5bd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="w3formorm",
            index=models.Index(
                fields=["workspace"], name="public_core_workspa_c51395_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="w3formorm",
            index=models.Index(
                fields=["tenant_id", "workspace"], name="public_core_tenant__b7a528_idx"
            ),
        ),
    ]
