# Generated by Django 5.0.14 on 2026-03-11 20:41

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0017_researchmessage"),
        ("tenants", "0006_clientworkspace_usagerecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="C103EventORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_number",
                    models.CharField(
                        db_index=True,
                        help_text="8-digit or 10-digit API number (normalized to 8-digit)",
                        max_length=14,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("set_cement_plug", "Set Cement Plug"),
                            ("set_surface_plug", "Set Surface Plug"),
                            ("set_bridge_plug", "Set Bridge Plug (CIBP)"),
                            ("set_marker", "Set Marker"),
                            ("squeeze", "Squeeze Operation"),
                            ("tag_toc", "Tag Top of Cement"),
                            ("circulate", "Circulate"),
                            ("pump_cement", "Pump Cement"),
                            ("woc", "Wait on Cement"),
                            ("pressure_test", "Pressure Test"),
                            ("pull_tubing", "Pull Tubing"),
                            ("cut_casing", "Cut Casing"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField(db_index=True)),
                ("event_start_time", models.TimeField(blank=True, null=True)),
                ("event_end_time", models.TimeField(blank=True, null=True)),
                ("depth_top_ft", models.FloatField(blank=True, null=True)),
                ("depth_bottom_ft", models.FloatField(blank=True, null=True)),
                ("tagged_depth_ft", models.FloatField(blank=True, null=True)),
                (
                    "cement_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Class A"),
                            ("B", "Class B"),
                            ("C", "Class C"),
                            ("G", "Class G"),
                            ("H", "Class H"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "sacks",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("volume_bbl", models.FloatField(blank=True, null=True)),
                ("pressure_psi", models.FloatField(blank=True, null=True)),
                ("plug_number", models.IntegerField(blank=True, null=True)),
                ("raw_event_detail", models.TextField(blank=True)),
                ("casing_string", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["event_date", "event_start_time"],
            },
        ),
        migrations.CreateModel(
            name="C103FormORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_number", models.CharField(db_index=True, max_length=14)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("noi", "Notice of Intent"),
                            ("subsequent", "Subsequent Report"),
                        ],
                        db_index=True,
                        default="noi",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("internal_review", "Internal Review"),
                            ("engineer_approved", "Engineer Approved"),
                            ("filed", "Filed with Agency"),
                            ("agency_approved", "Agency Approved"),
                            ("agency_rejected", "Agency Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("region", models.CharField(blank=True, max_length=30)),
                ("sub_area", models.CharField(blank=True, max_length=50, null=True)),
                ("coa_figure", models.CharField(blank=True, max_length=5)),
                (
                    "lease_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("state", "State"),
                            ("fee", "Fee"),
                            ("federal", "Federal"),
                            ("indian", "Indian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plan_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete C-103 plan JSON (header, plugs, compliance, narrative)",
                    ),
                ),
                ("proposed_work_narrative", models.TextField(blank=True)),
                ("compliance_violations", models.JSONField(blank=True, default=list)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nmocd_confirmation_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "C-103 Form",
                "verbose_name_plural": "C-103 Forms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="C103PlugORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plug_number", models.IntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("cement_plug", "Cement Plug"),
                            ("formation_plug", "Formation Plug"),
                            ("cibp_cap", "CIBP Cap"),
                            ("shoe_plug", "Shoe Plug"),
                            ("surface_plug", "Surface Plug"),
                            ("duqw_plug", "DUQW Plug"),
                            ("fill_plug", "Fill Plug"),
                            ("mechanical_plug", "Mechanical Plug"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("spot", "Spot"),
                            ("squeeze", "Squeeze"),
                            ("circulate", "Circulate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hole_type",
                    models.CharField(
                        choices=[("cased", "Cased Hole"), ("open", "Open Hole")],
                        max_length=10,
                    ),
                ),
                ("top_ft", models.FloatField()),
                ("bottom_ft", models.FloatField()),
                (
                    "cement_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Class A"),
                            ("B", "Class B"),
                            ("C", "Class C"),
                            ("G", "Class G"),
                            ("H", "Class H"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "sacks_required",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("inside_sacks", models.FloatField(blank=True, null=True)),
                ("outside_sacks", models.FloatField(blank=True, null=True)),
                ("excess_factor", models.FloatField(default=0.5)),
                ("formation_name", models.CharField(blank=True, max_length=100)),
                ("tag_required", models.BooleanField(default=True)),
                ("wait_hours", models.IntegerField(default=4)),
                ("procedure_narrative", models.TextField(blank=True)),
                ("regulatory_basis", models.CharField(blank=True, max_length=200)),
                ("casing_size_in", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["plug_number"],
            },
        ),
        migrations.CreateModel(
            name="DailyWorkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                ("day_number", models.IntegerField(default=1)),
                ("daily_narrative", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["work_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalC103FormORM",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("api_number", models.CharField(db_index=True, max_length=14)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("noi", "Notice of Intent"),
                            ("subsequent", "Subsequent Report"),
                        ],
                        db_index=True,
                        default="noi",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("internal_review", "Internal Review"),
                            ("engineer_approved", "Engineer Approved"),
                            ("filed", "Filed with Agency"),
                            ("agency_approved", "Agency Approved"),
                            ("agency_rejected", "Agency Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("region", models.CharField(blank=True, max_length=30)),
                ("sub_area", models.CharField(blank=True, max_length=50, null=True)),
                ("coa_figure", models.CharField(blank=True, max_length=5)),
                (
                    "lease_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("state", "State"),
                            ("fee", "Fee"),
                            ("federal", "Federal"),
                            ("indian", "Indian"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plan_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete C-103 plan JSON (header, plugs, compliance, narrative)",
                    ),
                ),
                ("proposed_work_narrative", models.TextField(blank=True)),
                ("compliance_violations", models.JSONField(blank=True, default=list)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nmocd_confirmation_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical C-103 Form",
                "verbose_name_plural": "historical C-103 Forms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RenameIndex(
            model_name="researchsession",
            new_name="public_core_api_num_a946e0_idx",
            old_name="public_core_api_num_state_status_idx",
        ),
        migrations.AddField(
            model_name="c103eventorm",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c103_events",
                to="public_core.wellregistry",
            ),
        ),
        migrations.AddField(
            model_name="c103formorm",
            name="plan_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="c103_forms",
                to="public_core.plansnapshot",
            ),
        ),
        migrations.AddField(
            model_name="c103formorm",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c103_forms",
                to="public_core.wellregistry",
            ),
        ),
        migrations.AddField(
            model_name="c103formorm",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="c103_forms",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddField(
            model_name="c103eventorm",
            name="c103_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="public_core.c103formorm",
            ),
        ),
        migrations.AddField(
            model_name="c103plugorm",
            name="c103_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plugs",
                to="public_core.c103formorm",
            ),
        ),
        migrations.AddField(
            model_name="dailyworkrecord",
            name="c103_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_work_records",
                to="public_core.c103formorm",
            ),
        ),
        migrations.AddField(
            model_name="dailyworkrecord",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="daily_records", to="public_core.c103eventorm"
            ),
        ),
        migrations.AddField(
            model_name="historicalc103formorm",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalc103formorm",
            name="plan_snapshot",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="public_core.plansnapshot",
            ),
        ),
        migrations.AddField(
            model_name="historicalc103formorm",
            name="well",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="public_core.wellregistry",
            ),
        ),
        migrations.AddField(
            model_name="historicalc103formorm",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddIndex(
            model_name="c103formorm",
            index=models.Index(
                fields=["api_number", "status"], name="public_core_api_num_d5b04a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c103formorm",
            index=models.Index(
                fields=["well", "-created_at"], name="public_core_well_id_7d42b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c103formorm",
            index=models.Index(
                fields=["tenant_id"], name="public_core_tenant__f8631c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c103formorm",
            index=models.Index(
                fields=["workspace"], name="public_core_workspa_1a649d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c103formorm",
            index=models.Index(
                fields=["tenant_id", "workspace"], name="public_core_tenant__b47988_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c103formorm",
            index=models.Index(
                fields=["api_number", "form_type"],
                name="public_core_api_num_d78e1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="c103eventorm",
            index=models.Index(
                fields=["api_number", "event_date"],
                name="public_core_api_num_1a5fac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="c103eventorm",
            index=models.Index(
                fields=["well", "event_date"], name="public_core_well_id_6f3d5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="c103plugorm",
            index=models.Index(
                fields=["c103_form", "plug_number"],
                name="public_core_c103_fo_a88d35_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyworkrecord",
            unique_together={("c103_form", "work_date")},
        ),
    ]
