# Generated by Django 5.0.14 on 2026-03-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public_core",
            "0018_c103eventorm_c103formorm_c103plugorm_dailyworkrecord_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="c103eventorm",
            name="api_number",
            field=models.CharField(
                db_index=True,
                help_text="8-digit or 10-digit API number (normalized to 8-digit)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="c103formorm",
            name="api_number",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="historicalc103formorm",
            name="api_number",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
