# Generated by Django 5.0.14 on 2026-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0019_alter_c103eventorm_api_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wellregistry",
            name="api14",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
