# Generated by Django 5.0.14 on 2026-03-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0020_alter_wellregistry_api14"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extracteddocument",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("rrc", "RRC - Public Regulator Data"),
                    ("tenant_upload", "Tenant Upload - User Provided"),
                    ("operator_packet", "Operator Packet - Approved Execution Plan"),
                ],
                db_index=True,
                default="rrc",
                help_text="Origin of document: RRC public data or tenant upload",
                max_length=16,
            ),
        ),
    ]
