# Generated by Django 5.0.14 on 2026-03-15 14:23

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0021_alter_extracteddocument_source_type"),
        ("tenants", "0006_clientworkspace_usagerecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalW3WizardSession",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("api_number", models.CharField(db_index=True, max_length=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("uploading", "uploading"),
                            ("parsing", "parsing"),
                            ("parsed", "parsed"),
                            ("reconciled", "reconciled"),
                            ("justifying", "justifying"),
                            ("ready", "ready"),
                            ("generating", "generating"),
                            ("completed", "completed"),
                            ("abandoned", "abandoned"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1,
                        help_text="1=upload, 2=review, 3=reconciliation, 4=justification, 5=generate",
                    ),
                ),
                (
                    "uploaded_documents",
                    models.JSONField(
                        default=list,
                        help_text="List of {file_name, file_type, storage_key, uploaded_at, size_bytes}",
                    ),
                ),
                (
                    "parse_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full DWRParseResult as dict",
                    ),
                ),
                (
                    "reconciliation_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full ReconciliationResult as dict",
                    ),
                ),
                (
                    "justifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{plug_number: {note, resolved, resolved_by, resolved_at}}",
                    ),
                ),
                ("w3_generation_result", models.JSONField(blank=True, default=dict)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_by",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("last_accessed_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "w3_form",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="public_core.w3formorm",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="public_core.wellregistry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tenants.clientworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical W-3 Wizard Session",
                "verbose_name_plural": "historical W-3 Wizard Sessions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="W3WizardSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("api_number", models.CharField(db_index=True, max_length=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("uploading", "uploading"),
                            ("parsing", "parsing"),
                            ("parsed", "parsed"),
                            ("reconciled", "reconciled"),
                            ("justifying", "justifying"),
                            ("ready", "ready"),
                            ("generating", "generating"),
                            ("completed", "completed"),
                            ("abandoned", "abandoned"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1,
                        help_text="1=upload, 2=review, 3=reconciliation, 4=justification, 5=generate",
                    ),
                ),
                (
                    "uploaded_documents",
                    models.JSONField(
                        default=list,
                        help_text="List of {file_name, file_type, storage_key, uploaded_at, size_bytes}",
                    ),
                ),
                (
                    "parse_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full DWRParseResult as dict",
                    ),
                ),
                (
                    "reconciliation_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full ReconciliationResult as dict",
                    ),
                ),
                (
                    "justifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{plug_number: {note, resolved, resolved_by, resolved_at}}",
                    ),
                ),
                ("w3_generation_result", models.JSONField(blank=True, default=dict)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_by",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="w3_wizard_sessions",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "w3_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="w3_wizard_sessions",
                        to="public_core.w3formorm",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="w3_wizard_sessions",
                        to="public_core.wellregistry",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="w3_wizard_sessions",
                        to="tenants.clientworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "W-3 Wizard Session",
                "verbose_name_plural": "W-3 Wizard Sessions",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="public_core_tenant__42fc94_idx",
                    ),
                    models.Index(
                        fields=["api_number", "tenant_id"],
                        name="public_core_api_num_486018_idx",
                    ),
                    models.Index(
                        fields=["well", "status"], name="public_core_well_id_a1be47_idx"
                    ),
                    models.Index(
                        fields=["workspace", "status"],
                        name="public_core_workspa_115f72_idx",
                    ),
                ],
            },
        ),
    ]
