# Generated by Django 5.0.14 on 2026-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0022_w3_wizard_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalw3wizardsession",
            name="plan_import_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="w3wizardsession",
            name="plan_import_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalw3wizardsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("uploading", "uploading"),
                    ("importing_plan", "importing_plan"),
                    ("parsing", "parsing"),
                    ("parsed", "parsed"),
                    ("reconciled", "reconciled"),
                    ("justifying", "justifying"),
                    ("ready", "ready"),
                    ("generating", "generating"),
                    ("completed", "completed"),
                    ("abandoned", "abandoned"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="w3wizardsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("uploading", "uploading"),
                    ("importing_plan", "importing_plan"),
                    ("parsing", "parsing"),
                    ("parsed", "parsed"),
                    ("reconciled", "reconciled"),
                    ("justifying", "justifying"),
                    ("ready", "ready"),
                    ("generating", "generating"),
                    ("completed", "completed"),
                    ("abandoned", "abandoned"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
    ]
