# Generated by Django 5.0.14 on 2026-03-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0025_plansnapshot_well_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalw3wizardsession",
            name="wbd_image_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to captured as-plugged wellbore diagram PNG",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="w3wizardsession",
            name="wbd_image_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path to captured as-plugged wellbore diagram PNG",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="historicalw3wizardsession",
            name="current_step",
            field=models.IntegerField(
                default=1,
                help_text="1=upload, 2=review, 3=reconciliation, 4=justification, 5=as-plugged-diagram, 6=generate",
            ),
        ),
        migrations.AlterField(
            model_name="w3wizardsession",
            name="current_step",
            field=models.IntegerField(
                default=1,
                help_text="1=upload, 2=review, 3=reconciliation, 4=justification, 5=as-plugged-diagram, 6=generate",
            ),
        ),
    ]
