# Generated by Django 5.0.14 on 2026-03-20 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0026_historicalw3wizardsession_wbd_image_path_and_more"),
        ("tenants", "0006_clientworkspace_usagerecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchsession",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_sessions",
                to="tenants.tenant",
            ),
        ),
    ]
