# Generated by Django 5.0.14 on 2026-03-20 23:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0027_add_tenant_to_research_session"),
        ("tenants", "0006_clientworkspace_usagerecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("casing", "Casing"),
                            ("tubing", "Tubing"),
                            ("liner", "Liner"),
                            ("cement_plug", "Cement Plug"),
                            ("bridge_plug", "Bridge Plug"),
                            ("packer", "Packer"),
                            ("retainer", "Retainer"),
                            ("perforation", "Perforation"),
                            ("cement_job", "Cement Job"),
                            ("formation_top", "Formation Top"),
                            ("dv_tool", "DV Tool"),
                            ("straddle_packer", "Straddle Packer"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("tenant", "Tenant"),
                            ("plan_proposed", "Plan Proposed"),
                            ("execution_actual", "Execution Actual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("installed", "Installed"),
                            ("proposed_addition", "Proposed Addition"),
                            ("proposed_removal", "Proposed Removal"),
                            ("removed", "Removed"),
                            ("modified", "Modified"),
                        ],
                        default="installed",
                        max_length=20,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "top_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "bottom_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "depth_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "outside_dia_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "inside_dia_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hole_size_in",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_ppf",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, default="", max_length=32)),
                (
                    "thread_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "cement_top_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cement_class",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "sacks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "source_document_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("as_of", models.DateTimeField(blank=True, null=True)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_components",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="public_core.wellcomponent",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="public_core.wellregistry",
                    ),
                ),
                (
                    "wizard_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_components",
                        to="public_core.w3wizardsession",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="well_components",
                        to="tenants.clientworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_well_component",
                "ordering": ["well", "sort_order", "top_ft"],
                "indexes": [
                    models.Index(
                        fields=["well", "layer", "lifecycle_state"],
                        name="public_core_well_id_7edb35_idx",
                    ),
                    models.Index(
                        fields=["well", "tenant_id", "layer"],
                        name="public_core_well_id_cad50c_idx",
                    ),
                    models.Index(
                        fields=["plan_snapshot", "component_type"],
                        name="public_core_plan_sn_2be0a1_idx",
                    ),
                    models.Index(
                        fields=["well", "component_type", "lifecycle_state"],
                        name="public_core_well_id_14866a_idx",
                    ),
                    models.Index(
                        fields=["wizard_session"], name="public_core_wizard__0135c0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WellComponentSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline"),
                            ("pre_plugging", "Pre-Plugging"),
                            ("post_plugging", "Post-Plugging"),
                            ("tenant_override", "Tenant Override"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "snapshot_data",
                    models.JSONField(
                        default=dict, help_text="Resolved component list as JSON"
                    ),
                ),
                ("component_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_snapshots",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_snapshots",
                        to="public_core.wellregistry",
                    ),
                ),
                (
                    "wizard_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_snapshots",
                        to="public_core.w3wizardsession",
                    ),
                ),
            ],
            options={
                "db_table": "public_core_well_component_snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["well", "context"],
                        name="public_core_well_id_647168_idx",
                    ),
                    models.Index(
                        fields=["well", "tenant_id"],
                        name="public_core_well_id_579c46_idx",
                    ),
                    models.Index(
                        fields=["plan_snapshot"], name="public_core_plan_sn_d6720a_idx"
                    ),
                    models.Index(
                        fields=["wizard_session"], name="public_core_wizard__0ea4a0_idx"
                    ),
                ],
            },
        ),
    ]
