# Generated by Django 5.0.14 on 2026-03-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0029_neubus_pipeline"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="extracteddocument",
            new_name="public_core_neubus__935e6e_idx",
            old_name="public_core_neubus__filename_idx",
        ),
        migrations.RenameIndex(
            model_name="neubusdocument",
            new_name="public_core_api_dc520b_idx",
            old_name="public_core_neubus_doc_api_idx",
        ),
        migrations.RenameIndex(
            model_name="neubusdocument",
            new_name="public_core_classif_597652_idx",
            old_name="public_core_neubus_doc_cls_idx",
        ),
        migrations.RenameIndex(
            model_name="neubusdocument",
            new_name="public_core_extract_ccfc71_idx",
            old_name="public_core_neubus_doc_ext_idx",
        ),
        migrations.AlterField(
            model_name="neubusdocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="neubuslease",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
