# Generated by Django 5.0.14 on 2026-03-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public_core",
            "0030_rename_public_core_neubus__filename_idx_public_core_neubus__935e6e_idx_and_more",
        ),
        ("tenants", "0006_clientworkspace_usagerecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="neubusdocument",
            name="triage_confidence",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Confidence of API triage: high, medium, low, unidentified",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="neubusdocument",
            name="triage_pages_scanned",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of pages scanned during triage"
            ),
        ),
        migrations.AddField(
            model_name="wellregistry",
            name="data_status",
            field=models.CharField(
                choices=[
                    ("cold_storage", "Cold Storage"),
                    ("indexing", "Indexing"),
                    ("ready", "Ready"),
                ],
                db_index=True,
                default="cold_storage",
                help_text="Data pipeline status: cold_storage (PDFs only), indexing (in progress), ready (fully extracted)",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="wellregistry",
            index=models.Index(
                fields=["data_status"], name="public_core_data_st_af531b_idx"
            ),
        ),
    ]
