# Generated by Django 5.0.14 on 2026-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0035_researchsession_force_fetch"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsegment",
            name="attribution_api",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Resolved API14 for this segment based on text analysis",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentsegment",
            name="attribution_confidence",
            field=models.CharField(
                choices=[
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("unresolved", "Unresolved"),
                ],
                default="unresolved",
                help_text="Confidence of segment-level well attribution",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documentsegment",
            name="attribution_method",
            field=models.CharField(
                default="unresolved",
                help_text="Method used for segment attribution (e.g., segment_text_api, segment_text_well_no, unresolved)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="extracteddocument",
            name="attribution_confidence",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                db_index=True,
                default="low",
                help_text="Confidence level of well attribution: high (extracted API), medium (cross-ref), low (session fallback)",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="extracteddocument",
            name="attribution_method",
            field=models.CharField(
                default="session_fallback",
                help_text="Method used to determine well attribution (e.g., extracted_api, well_no+lease_id, session_fallback)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="researchsession",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible metadata store (e.g., lease_well_map for cross-reference during extraction)",
            ),
        ),
        migrations.AddIndex(
            model_name="extracteddocument",
            index=models.Index(
                fields=["attribution_confidence"], name="public_core_attribu_f70ea3_idx"
            ),
        ),
    ]
