# Generated by Django 5.0.14 on 2026-03-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0036_well_attribution_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="neubusdocument",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a chunk, points to the original full document",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="public_core.neubusdocument",
            ),
        ),
        migrations.AddField(
            model_name="neubusdocument",
            name="part_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="1-based chunk index (None = not a chunk)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="neubusdocument",
            name="part_total",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total number of chunks (None = not a chunk)",
                null=True,
            ),
        ),
    ]
