# Generated by Django 5.0.14 on 2026-03-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0037_add_neubus_document_chunking"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="extracteddocument",
            name="public_core_api_num_685bef_idx",
        ),
        migrations.AddField(
            model_name="extracteddocument",
            name="is_stale",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marked True when extraction prompts change; forces re-extraction on next plan generation.",
            ),
        ),
        migrations.AlterField(
            model_name="neubusdocument",
            name="classification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("chunked", "Chunked"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="extracteddocument",
            index=models.Index(
                fields=[
                    "api_number",
                    "source_path",
                    "document_type",
                    "status",
                    "is_stale",
                ],
                name="public_core_api_num_703ead_idx",
            ),
        ),
    ]
