# Generated by Django 5.0.14 on 2026-04-06 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_core", "0039_w3wizardsession_formation_audit_compliance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="W3ASourceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_number",
                    models.CharField(
                        db_index=True,
                        help_text="14-digit API number that was queried",
                        max_length=14,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        help_text="Jurisdiction of the well (TX or NM)", max_length=4
                    ),
                ),
                (
                    "input_mode",
                    models.CharField(
                        choices=[
                            (
                                "extractions",
                                "Extractions — sourced from automated extraction pipeline",
                            ),
                            (
                                "user_files",
                                "User Files — sourced from user-uploaded documents",
                            ),
                            (
                                "hybrid",
                                "Hybrid — combination of extractions and user files",
                            ),
                            ("manual", "Manual — manually supplied data"),
                        ],
                        help_text="How input documents were sourced for this request",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success — documents found and returned"),
                            (
                                "no_records",
                                "No Records — API number not found in registry",
                            ),
                            (
                                "no_documents",
                                "No Documents — records found but no PDFs attached",
                            ),
                            ("error", "Error — exception or downstream failure"),
                        ],
                        db_index=True,
                        help_text="Overall result of the W3A initial endpoint call",
                        max_length=20,
                    ),
                ),
                (
                    "outcome_detail",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable detail about what happened (e.g. error message, reason for no-records)",
                    ),
                ),
                (
                    "document_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of PDFs found or combined during this request",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rrc", "RRC — fetched live from Texas RRC"),
                            ("cache", "Cache — returned from cached/stored data"),
                            (
                                "user_upload",
                                "User Upload — provided by user file upload",
                            ),
                        ],
                        help_text="Where the documents originated (rrc / cache / user_upload)",
                        max_length=20,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant that made this request",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this request (null for system/background requests)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="w3a_source_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "public_core_w3a_source_audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["outcome", "created_at"],
                        name="public_core_outcome_3d7c7b_idx",
                    ),
                    models.Index(
                        fields=["api_number", "created_at"],
                        name="public_core_api_num_38b2c1_idx",
                    ),
                ],
            },
        ),
    ]
