# Generated by Django 5.0.14 on 2025-11-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantplan"),
        migrations.swappable_dependency(settings.PLANS_PLAN_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantplan",
            name="feature_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "features",
                    models.JSONField(default=dict),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to=settings.PLANS_PLAN_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
            },
        ),
    ]


