# Generated by Django 5.0.14 on 2026-02-10 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_deleted_tenant_backup_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Client/operator name (e.g., 'Acme Oil Co')",
                        max_length=255,
                    ),
                ),
                (
                    "operator_number",
                    models.CharField(
                        blank=True, help_text="RRC operator number", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional notes about this client"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive workspaces are archived"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client Workspace",
                "verbose_name_plural": "Client Workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("plan_generated", "Plan Generated"),
                            ("extraction_completed", "Extraction Completed"),
                            ("ai_chat_message", "AI Chat Message"),
                            ("api_call", "API Call"),
                            ("document_uploaded", "Document Uploaded"),
                            ("plan_modified", "Plan Modified"),
                        ],
                        db_index=True,
                        help_text="Type of usage event",
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Resource type (e.g., 'well', 'plan', 'document')",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the resource (e.g., API number, plan ID, document ID)",
                        max_length=100,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="AI tokens consumed (for AI operations)"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0, help_text="Processing time in milliseconds"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event-specific data: model used, endpoint, parameters, etc.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this usage event occurred",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "db_table": "tenants_usage_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="deletedtenantbackup",
            new_name="tenants_del_soft_de_8de7a7_idx",
            old_name="tenants_del_soft_de_idx",
        ),
        migrations.RenameIndex(
            model_name="deletedtenantbackup",
            new_name="tenants_del_schedul_41d68c_idx",
            old_name="tenants_del_schedul_idx",
        ),
        migrations.AddField(
            model_name="clientworkspace",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspaces",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this usage is attributed to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this event (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Client workspace this usage is attributed to (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_records",
                to="tenants.clientworkspace",
            ),
        ),
        migrations.AddIndex(
            model_name="clientworkspace",
            index=models.Index(
                fields=["tenant", "is_active"], name="tenants_cli_tenant__5ffd72_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientworkspace",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "-created_at"], name="tenants_usa_tenant__5e633d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "event_type", "-created_at"],
                name="tenants_usa_tenant__9becc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["workspace", "-created_at"],
                name="tenants_usa_workspa_f10086_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="tenants_usa_event_t_6c06f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["user", "-created_at"], name="tenants_usa_user_id_e099f2_idx"
            ),
        ),
    ]
