# Generated by Django 5.0.14 on 2026-04-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenant_owner_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPlanningConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_plug_length_ft",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "min_plug_length_ft",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_combined_plugs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "use_cibp",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("when_perforated", "When perforated"),
                            ("never", "Never"),
                        ],
                        default="when_perforated",
                        max_length=20,
                    ),
                ),
                ("cibp_cap_ft", models.PositiveIntegerField(default=100)),
                ("use_bailer_method", models.BooleanField(default=False)),
                (
                    "use_cement_retainer",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("when_required", "When required by regulation"),
                            ("never", "Never"),
                        ],
                        default="when_required",
                        max_length=20,
                    ),
                ),
                ("cement_to_surface", models.BooleanField(default=True)),
                ("cased_hole_excess_factor", models.FloatField(default=0.5)),
                ("open_hole_excess_factor", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_config",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Planning Config",
                "verbose_name_plural": "Tenant Planning Configs",
            },
        ),
    ]
