# Generated by Django 5.0.14 on 2025-11-02 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("public_core", "0005_plansnapshot_status_historicalplansnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="Tenant who owns this conversation"
                    ),
                ),
                (
                    "openai_thread_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="OpenAI Assistants API thread ID for conversation continuity",
                        max_length=128,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional user-provided title",
                        max_length=256,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        default="assistant",
                        help_text="Conversation mode: 'assistant' (OpenAI) or 'tool' (direct tool calls)",
                        max_length=32,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False if thread is archived/closed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of most recent message",
                        null=True,
                    ),
                ),
                (
                    "baseline_plan",
                    models.ForeignKey(
                        help_text="Original baseline plan being discussed/modified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Owner with full edit rights",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_chat_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Latest modified plan snapshot (starts as baseline)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_chat_threads",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can view this thread (read-only access)",
                        related_name="shared_chat_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to="public_core.wellregistry",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_chat_threads",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content")),
                (
                    "openai_message_id",
                    models.CharField(
                        blank=True, help_text="OpenAI message ID", max_length=128
                    ),
                ),
                (
                    "openai_run_id",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI run ID (for assistant responses)",
                        max_length=128,
                    ),
                ),
                (
                    "tool_calls",
                    models.JSONField(
                        default=list,
                        help_text="List of tool calls made by assistant: [{name, arguments, call_id}, ...]",
                    ),
                ),
                (
                    "tool_results",
                    models.JSONField(
                        default=list,
                        help_text="Results of tool calls: [{call_id, result, status}, ...]",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata: model used, tokens, latency, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.chatthread",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "op_type",
                    models.CharField(
                        choices=[
                            ("combine_plugs", "Combine Plugs"),
                            ("replace_cibp", "Replace CIBP with Long Plug"),
                            ("adjust_interval", "Adjust Depth Interval"),
                            ("change_materials", "Change Materials"),
                            ("add_step", "Add Step"),
                            ("remove_step", "Remove Step"),
                            ("reorder_steps", "Reorder Steps"),
                            ("custom", "Custom Modification"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the change"
                    ),
                ),
                (
                    "operation_payload",
                    models.JSONField(
                        help_text="Parameters for the operation: {step_ids, interval, materials, etc.}"
                    ),
                ),
                (
                    "diff",
                    models.JSONField(
                        help_text="JSON Patch or step-level diff showing what changed in the payload"
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Risk score 0.0-1.0 (higher = more divergence from baseline)",
                    ),
                ),
                (
                    "violations_delta",
                    models.JSONField(
                        default=list,
                        help_text="New violations introduced (or resolved) by this modification",
                    ),
                ),
                (
                    "is_applied",
                    models.BooleanField(
                        default=False,
                        help_text="True if this modification is currently applied to the active plan",
                    ),
                ),
                (
                    "is_reverted",
                    models.BooleanField(
                        default=False,
                        help_text="True if this modification was later reverted",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific message that triggered this modification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifications",
                        to="assistant.chatmessage",
                    ),
                ),
                (
                    "chat_thread",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chat thread that triggered this modification (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifications",
                        to="assistant.chatthread",
                    ),
                ),
                (
                    "result_snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plan snapshot after modification (kind='post_edit')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications_to",
                        to="public_core.plansnapshot",
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        help_text="Plan snapshot before modification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications_from",
                        to="public_core.plansnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_plan_modifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegulatorOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        default="RRC",
                        help_text="Regulatory agency (e.g., 'RRC', 'EPA')",
                        max_length=64,
                    ),
                ),
                (
                    "filing_number",
                    models.CharField(
                        blank=True,
                        help_text="Agency filing/permit number",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not yet filed"),
                            ("under_review", "Under Review - RRC reviewing"),
                            ("approved", "Approved - RRC approved"),
                            ("rejected", "Rejected - RRC rejected"),
                            (
                                "revision_requested",
                                "Revision Requested - RRC requested changes",
                            ),
                            ("withdrawn", "Withdrawn - Filing withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "filed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When plan was submitted to RRC",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When RRC completed review", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When RRC approved (if approved)",
                        null=True,
                    ),
                ),
                (
                    "review_duration_days",
                    models.IntegerField(
                        blank=True, help_text="Days from filed to decision", null=True
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Notes/comments from RRC reviewer"
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of RRC reviewer (if known)",
                        max_length=128,
                    ),
                ),
                (
                    "revision_count",
                    models.IntegerField(
                        default=0, help_text="Number of revisions requested/submitted"
                    ),
                ),
                (
                    "revision_notes",
                    models.JSONField(
                        default=list,
                        help_text="List of revision requests: [{date, reason, resolved}, ...]",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Confidence score 0.0-1.0 based on approval history",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "influenced_by_modifications",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Modifications that influenced this plan",
                        related_name="influenced_outcomes",
                        to="assistant.planmodification",
                    ),
                ),
                (
                    "plan_snapshot",
                    models.OneToOneField(
                        help_text="Plan that was filed with RRC",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulator_outcome",
                        to="public_core.plansnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "assistant_regulator_outcomes",
            },
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="assistant_c_tenant__635f1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["well", "-created_at"], name="assistant_c_well_id_09924e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["tenant_id", "is_active", "-updated_at"],
                name="assistant_c_tenant__99f42b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="assistant_c_thread__ae701a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["role", "created_at"], name="assistant_c_role_45e2e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planmodification",
            index=models.Index(
                fields=["source_snapshot", "-created_at"],
                name="assistant_p_source__f78e1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planmodification",
            index=models.Index(
                fields=["chat_thread", "-created_at"],
                name="assistant_p_chat_th_bae9e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planmodification",
            index=models.Index(
                fields=["applied_by", "-created_at"],
                name="assistant_p_applied_0ac1b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planmodification",
            index=models.Index(
                fields=["is_applied", "is_reverted"],
                name="assistant_p_is_appl_3856d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoroutcome",
            index=models.Index(
                fields=["status", "-filed_at"], name="assistant_r_status_843365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoroutcome",
            index=models.Index(
                fields=["agency", "status"], name="assistant_r_agency_8383fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regulatoroutcome",
            index=models.Index(
                fields=["-approved_at"], name="assistant_r_approve_813292_idx"
            ),
        ),
    ]
